name: 'Push with Status Checks'
description: 'Push local workflow commit(s) to protected branches with required status checks.'
author: 'Casper Welzel Andersen (CasperWA)'
branding:
  icon: shield
  color: purple
inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'Repository name to push to. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: '${{ github.repository }}'
    required: false
  branch:
    description: 'Target branch for the push.'
    required: false
    default: 'master'
  changes:
    description: 'Shell script to run in the target repository root prior to the push. NOTE: Unrelated to prior workflow jobs and steps. MUST be a file in the repository that spawns the workflow. MUST be a relative path from the repository root, e.g., `.github/workflows/changes.sh`'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
