name: 'Push to Status Check-Protected Branches'
description: 'Push local workflow commit(s) to protected branches with required status checks.'
author: 'Casper Welzel Andersen'
branding:
  icon: shield
  color: purple
inputs:
  token:
    description: 'Token for the repo.'
    required: false
  branch:
    description: 'Target branch for the push. Mutually exclusive with "ref". Example: "main".'
    required: true
    default: 'false'
  ref:
    description: 'Target ref for the push. Mutually exclusive with "branch". Example: "refs/heads/main".'
    required: true
    default: 'false'
  force:
    description: 'Determines if --force is used.'
    required: true
    default: 'false'
  tags:
    description: 'Determines if --tags is used.'
    required: true
    default: 'false'
  interval:
    description: 'Time interval (in seconds) between each new check, when waiting for status checks to complete'
    required: true
    default: '1'
  timeout:
    description: 'Time (in minutes) of how long the action should run before timing out, waiting for status checks to complete'
    required: true
    default: '1'
  sleep:
    description: "Time (in seconds) the action should wait until it will start 'waiting' and check the list of running actions/checks. This should be an appropriate number to let the checks start up"
    required: true
    default: '15'
  unprotect_reviews:
    description: 'Momentarily remove pull request review protection from target branch'
    required: false
    default: 'true'
  debug:
    description: 'Set `set -x` in `entrypoint.sh` when running the action. This is for debugging the action.'
    required: false
    default: 'false'
  path:
    description: 'A path to the working directory of the action. This should be relative to the $GITHUB_WORKSPACE.'
    required: true
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
