name: 'Push to Status Check-Protected Branches'
description: 'Push local workflow commit(s) to protected branches with required status checks.'
author: 'Casper Welzel Andersen'
branding:
  icon: shield
  color: purple
inputs:
  token:
    description: 'Token for the repo.'
    required: true
  branch:
    description: 'Target branch for the push. Mutually exclusive with "ref". Example: "main".'
    required: false
    default: ''
  ref:
    description: 'Target ref for the push. Mutually exclusive with "branch". Example: "refs/heads/main".'
    required: false
    default: ''
  force:
    description: 'Determines if --force is used.'
    required: false
    default: 'false'
  tags:
    description: 'Determines if --tags is used.'
    required: false
    default: 'false'
  interval:
    description: 'Time interval (in seconds) between each new check, when waiting for status checks to complete'
    required: false
    default: '30'
  timeout:
    description: 'Time (in minutes) of how long the action should run before timing out, waiting for status checks to complete'
    required: false
    default: '15'
  pre_sleep:
    description: "Time (in seconds) the action should wait until it will start 'waiting' and check the list of running actions/checks. This should be an appropriate number to let the checks start up"
    required: false
    default: '5'
  post_sleep:
    description: "Time (in seconds) the action should wait after it has finished 'waiting' for all checks to finish."
    required: false
    default: '5'
  unprotect_reviews:
    description: 'Momentarily remove pull request review protection from target branch'
    required: false
    default: 'false'
  debug:
    description: 'Set `set -x` in `entrypoint.sh` when running the action. This is for debugging the action.'
    required: false
    default: 'false'
  path:
    description: 'A path to the working directory of the action. This should be relative to the $GITHUB_WORKSPACE.'
    required: false
    default: '.'
  gh_rest_api_base_url:
    description: 'The base URL for the GitHub REST API. This is useful for GitHub Enterprise users. Note, `/api/v3` will be appended to this value if it does not already exist. See the note here: https://docs.github.com/en/enterprise-server@3.10/rest/quickstart?apiVersion=2022-11-28&tool=curl#using-curl-commands-in-github-actions.'
    required: false
    default: 'https://api.github.com'
  acceptable_conclusions:
    description: 'A comma-separated list of acceptable conclusions. If any of these conclusions are present, the action will not fail.'
    required: false
    default: 'success'
  fail_fast:
    description: 'If set to true, the action will fail as soon as a check fails. If set to false (default), the action will wait for all checks to complete before failing.'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
