#!/bin/bash
set -e

REPOSITORY=${INPUT_REPOSTORY}
REF=${INPUT_REF}
WORKING_DIRECTORY=${INPUT_DIRECTORY}

echo "REPOSTORY: ${INPUT_REPOSITORY}"
echo "REF: ${INPUT_REF}"
echo "DIRECTORY: ${INPUT_DIRECTORY}"
