name: CI Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:

  reset_test_branches:
    runs-on: ubuntu-latest
    name: Reset test branches
    steps:
    - name: Checkout action repo
      uses: actions/checkout@v2
      with:
        token: '${{ secrets.CI_RESET_TEST_BRANCHES }}'

    - name: Reset branches
      run: |
        python3 -m pip install -U pip
        pip install requests

        python3 -c "import requests; requests.delete('https://api.github.com/repos/CasperWA/push-protected/branches/protected/protection/enforce_admins', headers={'Authorization': 'token ${{ secrets.CI_RESET_TEST_BRANCHES }}'})"

        git fetch origin

        git branch not_protected origin/not_protected
        git branch protected origin/protected

        git checkout not_protected
        git reset --hard ${{ github.sha }}
        git push -f

        git checkout protected
        git reset --hard ${{ github.sha }}
        git push -f

        python3 -c "import requests; requests.post('https://api.github.com/repos/CasperWA/push-protected/branches/protected/protection/enforce_admins', headers={'Authorization': 'token ${{ secrets.CI_RESET_TEST_BRANCHES }}'})"

  not_protected:
    needs: reset_test_branches
    runs-on: ubuntu-latest
    name: Testing - non-protected
    steps:
    - name: Use local action (checkout)
      uses: actions/checkout@v2

    - name: Pushing to a non-protected branch
      uses: ./
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        repository: '${{ github.repository }}'
        branch: not_protected
        changes: .github/workflows/ci.sh
        extra_data: .github/extra_data.log,.github/workflows/extra_data_more.md

  protected:
    needs: reset_test_branches
    runs-on: ubuntu-latest
    name: Testing - protected
    steps:
    - name: Use local action (checkout)
      uses: actions/checkout@v2

    - name: Pushing to a protected branch
      uses: ./
      with:
        token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
        repository: '${{ github.repository }}'
        branch: protected
        changes: .github/workflows/ci.sh
        extra_data: .github/extra_data.log,.github/workflows/extra_data_more.md
