name: CI Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:

  reset_test_branches:
    runs-on: ubuntu-latest
    name: Reset test branches
    steps:
    - name: Checkout action repo
      uses: actions/checkout@v2
      with:
        token: '${{ secrets.CI_RESET_TEST_BRANCHES }}'

    - name: Reset branches
      run: |
        git fetch origin

        git branch not_protected origin/not_protected
        git branch protected origin/protected

        git checkout not_protected
        git reset --hard ${{ github.sha }}
        git push -f

        git checkout protected
        git reset --hard ${{ github.sha }}
        git push -f

  not_protected:
    needs: reset_test_branches
    runs-on: ubuntu-latest
    name: Testing - non-protected
    steps:
    - name: Pushing to a non-protected branch
      uses: 'CasperWA/push-protected@${{ github.sha }}'
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        repository: '${{ github.repository }}'
        branch: 'not_protected'
        changes: .github/workflows/ci.sh

  protected:
    needs: reset_test_branches
    runs-on: ubuntu-latest
    name: Testing - protected
    steps:
    - name: Pushing to a protected branch
      uses: 'CasperWA/push-protected@${{ github.sha }}'
      with:
        token: '${{ secrets.CI_PUSH_TO_PROTECTED_BRANCH }}'
        repository: '${{ github.repository }}'
        branch: 'protected'
        changes: .github/workflows/ci.sh
