name: Release - updating vMAJOR tag

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'CasperWA/push-protected' && startsWith(github.ref, 'refs/tags/v')
    env:
      PUBLISH_UPDATE_BRANCH: master

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Update Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Update version and tags
      run: .github/utils/update_version.sh

    # This will not work as intended, since 'push-action/**' has not been added to `ci.yml`.
    # But it will be fine due to the powerful PAT.
    - name: Push updates to '${{ env.PUBLISH_UPDATE_BRANCH }}'
      uses: ./
      with:
        token: ${{ secrets.CI_RESET_TEST_BRANCHES }}
        branch: ${{ env.PUBLISH_UPDATE_BRANCH }}
        force: true
        tags: true
